# Generated by Django 4.1.3 on 2023-06-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
